"use client";

import { useActionState, useState } from "react";
import { createPackage, togglePackage, updatePackage, type PackageActionState } from "./actions";
import type { AdminPackage } from "@/lib/admin/packages";

const initial: PackageActionState = { error: null, success: null };
const sizes = ["citadine", "berline", "suv_medium", "suv_large", "moto_small", "moto_large"];

export function PackagesManager({ packages }: { packages: AdminPackage[] }) {
  const [showInactive, setShowInactive] = useState(true);
  const visible = packages.filter((item) => showInactive || item.is_active);
  return <div className="space-y-8"><section className="flex items-center gap-3"><h2 className="font-medium">Package catalog</h2><label className="text-sm"><input type="checkbox" checked={showInactive} onChange={(event) => setShowInactive(event.target.checked)} className="mr-2" />Show inactive</label></section><div className="space-y-4">{visible.map((item) => <PackageEditor key={item.id} item={item} />)}{visible.length === 0 && <p className="text-sm text-black/60">No packages match this filter.</p>}</div><NewPackageForm /></div>;
}

function PackageEditor({ item }: { item: AdminPackage }) {
  const [state, action, pending] = useActionState(updatePackage, initial);
  const [toggleState, toggleAction, toggling] = useActionState(togglePackage, initial);
  return <article className="max-w-3xl rounded border border-black/10 p-4"><div className="mb-3 flex items-center justify-between"><div><h3 className="font-medium">{item.name}</h3><p className="text-xs text-black/60">{item.id} · {item.vehicle_category} · {item.vehicle_size}</p></div><span className={item.is_active ? "text-sm text-green-700" : "text-sm text-black/50"}>{item.is_active ? "Active" : "Inactive"}</span></div><form action={action} className="grid grid-cols-2 gap-3"><input type="hidden" name="id" value={item.id} /><label className="space-y-1 text-sm"><span className="font-medium">Name</span><input name="name" defaultValue={item.name} className="w-full rounded border px-2 py-1.5" /></label><label className="space-y-1 text-sm"><span className="font-medium">Base price (MAD)</span><input name="base_price" defaultValue={item.base_price} type="number" min="0" step="0.01" className="w-full rounded border px-2 py-1.5" /></label><label className="col-span-2 space-y-1 text-sm"><span className="font-medium">Description</span><textarea name="description" defaultValue={item.description} className="w-full rounded border px-2 py-1.5" /></label><label className="space-y-1 text-sm"><span className="font-medium">Estimated duration (minutes)</span><input name="estimated_duration_minutes" defaultValue={item.estimated_duration_minutes} type="number" min="1" className="w-full rounded border px-2 py-1.5" /></label><div className="flex items-end gap-2"><button disabled={pending} className="rounded bg-black px-3 py-1.5 text-sm text-white">{pending ? "Saving..." : "Save changes"}</button></div></form><form action={toggleAction} className="mt-3"><input type="hidden" name="id" value={item.id} /><input type="hidden" name="is_active" value={String(item.is_active)} /><button disabled={toggling} className="text-sm underline">{item.is_active ? "Disable package" : "Enable package"}</button></form>{(state.error || toggleState.error) && <p className="mt-2 text-sm text-red-600">{state.error || toggleState.error}</p>}{(state.success || toggleState.success) && <p className="mt-2 text-sm text-green-700">{state.success || toggleState.success}</p>}</article>;
}

function NewPackageForm() {
  const [state, action, pending] = useActionState(createPackage, initial);
  return <section className="max-w-3xl border-t border-black/10 pt-6"><h2 className="mb-3 font-medium">Add package</h2><form action={action} className="grid grid-cols-2 gap-3"><label className="space-y-1 text-sm"><span className="font-medium">Package ID</span><input name="id" placeholder="wash_custom_citadine" required pattern="[a-z0-9_]+" className="w-full rounded border px-2 py-1.5" /></label><label className="space-y-1 text-sm"><span className="font-medium">Name</span><input name="name" required className="w-full rounded border px-2 py-1.5" /></label><label className="space-y-1 text-sm"><span className="font-medium">Vehicle category</span><select name="vehicle_category" required className="w-full rounded border px-2 py-1.5"><option value="car">Car</option><option value="moto">Moto</option></select></label><label className="space-y-1 text-sm"><span className="font-medium">Vehicle size</span><select name="vehicle_size" required className="w-full rounded border px-2 py-1.5">{sizes.map((size) => <option key={size} value={size}>{size}</option>)}</select></label><label className="space-y-1 text-sm"><span className="font-medium">Base price (MAD)</span><input name="base_price" type="number" min="0" step="0.01" required className="w-full rounded border px-2 py-1.5" /></label><label className="space-y-1 text-sm"><span className="font-medium">Estimated duration (minutes)</span><input name="estimated_duration_minutes" type="number" min="1" required className="w-full rounded border px-2 py-1.5" /></label><label className="col-span-2 space-y-1 text-sm"><span className="font-medium">Description</span><textarea name="description" required className="w-full rounded border px-2 py-1.5" /></label>{state.error && <p className="col-span-2 text-sm text-red-600">{state.error}</p>}{state.success && <p className="col-span-2 text-sm text-green-700">{state.success}</p>}<button disabled={pending} className="col-span-2 rounded bg-black px-3 py-2 text-sm text-white">{pending ? "Creating..." : "Add package"}</button></form></section>;
}
