-- Cleanup duplicate SEARCHING_WORKER rows generated by the old dispatch retry loop.
-- Keeps only the latest SEARCHING_WORKER row per booking as a reference record.
create or replace function cleanup_stale_searching_worker_rows()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_booking_id uuid;
  v_keep_id uuid;
begin
  for v_booking_id in select distinct booking_id from booking_assignments where status = 'SEARCHING_WORKER'
  loop
    select id into v_keep_id
    from booking_assignments
    where booking_id = v_booking_id and status = 'SEARCHING_WORKER'
    order by created_at desc
    limit 1;

    delete from booking_assignments
    where booking_id = v_booking_id
      and status = 'SEARCHING_WORKER'
      and id <> v_keep_id;
  end loop;
end;
$$;

revoke execute on function cleanup_stale_searching_worker_rows() from public, anon, authenticated;
